plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    namespace 'com.example.flutter_opencv_plugin'
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11 // Set to Java 11
        targetCompatibility JavaVersion.VERSION_11 // Set to Java 11
    }

    kotlinOptions {
        jvmTarget = '11' // Set to Java 11 to match compileOptions
    }

    defaultConfig {
        minSdk 30
        targetSdk 35
        ndkVersion "27.0.12077973"
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            debuggable true
        }
    }

    externalNativeBuild {
        cmake {
            path 'CMakeLists.txt'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/opencv']
        }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.8.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.0.21"
}