plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android' version '1.8.22' apply false
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace = "com.example.flutter_opencv_plugin"

    compileSdk = 35

    defaultConfig {
        minSdk = 21

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_static"
            }
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
            java.srcDirs = ['src/main/java', 'src/main/kotlin']
        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
            version "3.22.1"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }

    packagingOptions {
        pickFirst '**/*.so'
    }

    lint {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.22"
    testImplementation "org.jetbrains.kotlin:kotlin-test"
    testImplementation "org.mockito:mockito-core:5.0.0"
}
